name: "Self Audit Test"
on:
  pull_request: # Runs whenever you open a PR in this repo
permissions:
  contents: write
  pull-requests: write
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./ # 💡 Points to the current folder where your dist/index.js is
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.GROQ_API_KEY }}
        with:
          openai_base_url: https://api.groq.com/openai/v1
          openai_heavy_model: llama-3.3-70b-versatile
          create_remedy_pr: true 
          review_simple_changes: true
